// <auto-generated />
using System;
using API.src.Infra.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(BuildContext))]
    partial class BuildContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("API.Domain.Location.Address", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ExtraInfo")
                        .HasColumnType("longtext");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("API.Domain.RealState.Models.CondominiumObject", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Gym")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ValuesID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LocationID");

                    b.HasIndex("ValuesID");

                    b.ToTable("Condominiums");
                });

            modelBuilder.Entity("API.Domain.User.UserObject", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.src.Domain.Monetary.Entities.RealStateMonetary", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double?>("IPTU")
                        .HasColumnType("double");

                    b.Property<double>("montlyValue")
                        .HasColumnType("double");

                    b.HasKey("ID");

                    b.ToTable("RealStateMonetary");
                });

            modelBuilder.Entity("API.src.Domain.RealState.Entities.RealStateObject", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AdressID")
                        .HasColumnType("int");

                    b.Property<bool>("AllowPets")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentResidentID")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Furnished")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Garage")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RoomWithBathroom")
                        .HasColumnType("int");

                    b.Property<int>("Rooms")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("ValuesID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AdressID");

                    b.HasIndex("CurrentResidentID");

                    b.HasIndex("ValuesID");

                    b.ToTable("RealStates");

                    b.HasDiscriminator<string>("Discriminator").HasValue("RealStateObject");
                });

            modelBuilder.Entity("API.src.Domain.Values.CondominiumMonetary", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double?>("fireInsurence")
                        .HasColumnType("double");

                    b.Property<double>("montlyValue")
                        .HasColumnType("double");

                    b.Property<double?>("serviceCharge")
                        .HasColumnType("double");

                    b.HasKey("ID");

                    b.ToTable("CondominiumMonetary");
                });

            modelBuilder.Entity("API.src.Domain.RealState.Entities.RealStateWithCondo", b =>
                {
                    b.HasBaseType("API.src.Domain.RealState.Entities.RealStateObject");

                    b.Property<int?>("CondominioID")
                        .HasColumnType("int");

                    b.HasIndex("CondominioID");

                    b.ToTable("RealStates");

                    b.HasDiscriminator().HasValue("RealStateWithCondo");
                });

            modelBuilder.Entity("API.Domain.RealState.Models.CondominiumObject", b =>
                {
                    b.HasOne("API.Domain.Location.Address", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID");

                    b.HasOne("API.src.Domain.Values.CondominiumMonetary", "Values")
                        .WithMany()
                        .HasForeignKey("ValuesID");

                    b.Navigation("Location");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("API.src.Domain.RealState.Entities.RealStateObject", b =>
                {
                    b.HasOne("API.Domain.Location.Address", "Adress")
                        .WithMany()
                        .HasForeignKey("AdressID");

                    b.HasOne("API.Domain.User.UserObject", "CurrentResident")
                        .WithMany()
                        .HasForeignKey("CurrentResidentID");

                    b.HasOne("API.src.Domain.Monetary.Entities.RealStateMonetary", "Values")
                        .WithMany()
                        .HasForeignKey("ValuesID");

                    b.Navigation("Adress");

                    b.Navigation("CurrentResident");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("API.src.Domain.RealState.Entities.RealStateWithCondo", b =>
                {
                    b.HasOne("API.Domain.RealState.Models.CondominiumObject", "Condominio")
                        .WithMany("realStates")
                        .HasForeignKey("CondominioID");

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("API.Domain.RealState.Models.CondominiumObject", b =>
                {
                    b.Navigation("realStates");
                });
#pragma warning restore 612, 618
        }
    }
}
